### ISSUE TITLE
Not able to install DBD::DB2 on RHEL 9

### ISSUE THREAD

**Issue by Vani2468** [lausser/check_db2_health#9]
We are trying to install DBD::DB2 perl module for DB2 parameters Monitoring on RHEL 9 using check_db2_health plugin, but the module installation getting failed when I am running make command.

I have installed DBI module and DB2 driver before installing DBD::DB2 perl module.

Please find below module version

DBD::DB2 --> 1.85 (trying to install)
DBI --> 1.639 (Installed)
DB2 driver --> v11.1.4fp5_linuxx64_dsdriver and v11.1.4fp5_linuxx64_rtcl (Installed)
Perl --> v5.32.1 (Default on RHEL 9)

Kindly advice on how can I install  DBD::DB2 module on RHEL 9.

**Comment by lausser** [comment]
I have no idea. You have to ask the author of DBD::DB2.
